[package]
name = "lucy-cli"
version = "0.1.0"
authors = ["Haato3o <me@haato.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lucy = { path = "../lucy" }